"""regenerate

Revision ID: 3879a511ebc5
Revises: 629497f37f8f
Create Date: 2023-06-21 11:31:57.904928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3879a511ebc5'
down_revision = '629497f37f8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
