"""add a column

Revision ID: 4be0c2ca8f23
Revises: 7a316dcf50d8
Create Date: 2023-06-21 11:43:01.620465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be0c2ca8f23'
down_revision = '7a316dcf50d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('format', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'format')
    # ### end Alembic commands ###
