"""regenerate

Revision ID: 7a316dcf50d8
Revises: 3879a511ebc5
Create Date: 2023-06-21 11:33:18.691144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a316dcf50d8'
down_revision = '3879a511ebc5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
