"""create tables

Revision ID: e5f0e2d71679
Revises: 
Create Date: 2023-06-20 15:20:00.542500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5f0e2d71679'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_token')
    op.drop_table('user_mst')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_mst',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_cd', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ins_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('access_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('mail', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='user_mst_pkey')
    )
    op.create_table('user_token',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('upd_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('und_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('token', name='user_token_pkey')
    )
    # ### end Alembic commands ###
