"""create tables

Revision ID: fe62785dfd8b
Revises: e5f0e2d71679
Create Date: 2023-06-20 15:49:37.751584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe62785dfd8b'
down_revision = 'e5f0e2d71679'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
